// Re-export all services for convenient imports
export * from "./evaluation.service";
export * from "./rubric.service";
export * from "./allocation.service";
export * from "./dashboard.service";
export * from "./course.service";
export * from "./subject.service";
export * from "./student.service";
export * from "./project-assessment.service";
export * from "./competency.service";
export * from "./overview.service";
export * from "./feedback-summary.service";
export * from "./learning-objective.service";
export * from "./project-notes.service";
export * from "./client.service";
export * from "./project.service";
export * from "./project-team.service";
export * from "./omza.service";
export * from "./peer-feedback-results.service";
