"""add cluster and team_number to users

Revision ID: 10a4510f8374
Revises: 7525b9bfa8d2
Create Date: 2025-10-18 21:56:00.892371

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "10a4510f8374"
down_revision: Union[str, None] = "7525b9bfa8d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("cluster", sa.String(length=50), nullable=True))
    op.add_column("users", sa.Column("team_number", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_users_cluster"), "users", ["cluster"], unique=False)
    op.create_index(
        op.f("ix_users_team_number"), "users", ["team_number"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_team_number"), table_name="users")
    op.drop_index(op.f("ix_users_cluster"), table_name="users")
    op.drop_column("users", "team_number")
    op.drop_column("users", "cluster")
    # ### end Alembic commands ###
