"""add_project_plan_tables_and_level_field

Revision ID: 50c7ab3b2ada
Revises: de711157475c
Create Date: 2026-02-01 07:51:19.780349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c7ab3b2ada'
down_revision: Union[str, None] = 'de711157475c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('global_teacher_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_plan_project', 'project_plans', ['project_id'], unique=False)
    op.create_index('ix_project_plan_school', 'project_plans', ['school_id'], unique=False)
    op.create_index('ix_project_plan_status', 'project_plans', ['status'], unique=False)
    op.create_index(op.f('ix_project_plans_id'), 'project_plans', ['id'], unique=False)
    op.create_index(op.f('ix_project_plans_project_id'), 'project_plans', ['project_id'], unique=True)
    op.create_index(op.f('ix_project_plans_school_id'), 'project_plans', ['school_id'], unique=False)
    op.create_table('project_plan_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('project_plan_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('client_organisation', sa.String(length=200), nullable=True),
    sa.Column('client_contact', sa.String(length=200), nullable=True),
    sa.Column('client_email', sa.String(length=320), nullable=True),
    sa.Column('client_phone', sa.String(length=50), nullable=True),
    sa.Column('client_description', sa.Text(), nullable=True),
    sa.Column('teacher_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_plan_id'], ['project_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_plan_id', 'key', name='uq_project_plan_section_key')
    )
    op.create_index('ix_project_plan_section_plan', 'project_plan_sections', ['project_plan_id'], unique=False)
    op.create_index('ix_project_plan_section_status', 'project_plan_sections', ['status'], unique=False)
    op.create_index(op.f('ix_project_plan_sections_id'), 'project_plan_sections', ['id'], unique=False)
    op.create_index(op.f('ix_project_plan_sections_project_plan_id'), 'project_plan_sections', ['project_plan_id'], unique=False)
    op.create_index(op.f('ix_project_plan_sections_school_id'), 'project_plan_sections', ['school_id'], unique=False)
    op.drop_index(op.f('ix_attendance_aggregates_user_id'), table_name='attendance_aggregates')
    op.create_index(op.f('ix_attendance_aggregates_user_id'), 'attendance_aggregates', ['user_id'], unique=True)
    op.add_column('projects', sa.Column('level', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'level')
    op.drop_index(op.f('ix_attendance_aggregates_user_id'), table_name='attendance_aggregates')
    op.create_index(op.f('ix_attendance_aggregates_user_id'), 'attendance_aggregates', ['user_id'], unique=False)
    op.drop_index(op.f('ix_project_plan_sections_school_id'), table_name='project_plan_sections')
    op.drop_index(op.f('ix_project_plan_sections_project_plan_id'), table_name='project_plan_sections')
    op.drop_index(op.f('ix_project_plan_sections_id'), table_name='project_plan_sections')
    op.drop_index('ix_project_plan_section_status', table_name='project_plan_sections')
    op.drop_index('ix_project_plan_section_plan', table_name='project_plan_sections')
    op.drop_table('project_plan_sections')
    op.drop_index(op.f('ix_project_plans_school_id'), table_name='project_plans')
    op.drop_index(op.f('ix_project_plans_project_id'), table_name='project_plans')
    op.drop_index(op.f('ix_project_plans_id'), table_name='project_plans')
    op.drop_index('ix_project_plan_status', table_name='project_plans')
    op.drop_index('ix_project_plan_school', table_name='project_plans')
    op.drop_index('ix_project_plan_project', table_name='project_plans')
    op.drop_table('project_plans')
    # ### end Alembic commands ###
