"""Add project notes tables

Revision ID: 553d97716b1d
Revises: mt_20251112_01
Create Date: 2025-11-15 08:46:10.407718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '553d97716b1d'
down_revision: Union[str, None] = 'mt_20251112_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_notes_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('class_name', sa.String(length=50), nullable=True),
    sa.Column('evaluation_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_notes_context_created_by', 'project_notes_contexts', ['created_by'], unique=False)
    op.create_index('ix_project_notes_context_school_course', 'project_notes_contexts', ['school_id', 'course_id'], unique=False)
    op.create_index(op.f('ix_project_notes_contexts_class_name'), 'project_notes_contexts', ['class_name'], unique=False)
    op.create_index(op.f('ix_project_notes_contexts_course_id'), 'project_notes_contexts', ['course_id'], unique=False)
    op.create_index(op.f('ix_project_notes_contexts_created_by'), 'project_notes_contexts', ['created_by'], unique=False)
    op.create_index(op.f('ix_project_notes_contexts_evaluation_id'), 'project_notes_contexts', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_project_notes_contexts_id'), 'project_notes_contexts', ['id'], unique=False)
    op.create_index(op.f('ix_project_notes_contexts_school_id'), 'project_notes_contexts', ['school_id'], unique=False)
    op.create_table('project_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=False),
    sa.Column('note_type', sa.String(length=20), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('omza_category', sa.String(length=100), nullable=True),
    sa.Column('learning_objective_id', sa.Integer(), nullable=True),
    sa.Column('is_competency_evidence', sa.Boolean(), nullable=False),
    sa.Column('is_portfolio_evidence', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['project_notes_contexts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learning_objective_id'], ['learning_objectives.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_note_context_type', 'project_notes', ['context_id', 'note_type'], unique=False)
    op.create_index('ix_project_note_created_at', 'project_notes', ['created_at'], unique=False)
    op.create_index('ix_project_note_omza', 'project_notes', ['omza_category'], unique=False)
    op.create_index('ix_project_note_student', 'project_notes', ['student_id'], unique=False)
    op.create_index('ix_project_note_team', 'project_notes', ['team_id'], unique=False)
    op.create_index(op.f('ix_project_notes_context_id'), 'project_notes', ['context_id'], unique=False)
    op.create_index(op.f('ix_project_notes_created_by'), 'project_notes', ['created_by'], unique=False)
    op.create_index(op.f('ix_project_notes_id'), 'project_notes', ['id'], unique=False)
    op.create_index(op.f('ix_project_notes_learning_objective_id'), 'project_notes', ['learning_objective_id'], unique=False)
    op.create_index(op.f('ix_project_notes_student_id'), 'project_notes', ['student_id'], unique=False)
    op.create_index(op.f('ix_project_notes_team_id'), 'project_notes', ['team_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_school_id'), 'audit_logs', ['school_id'], unique=False)
    op.create_index(op.f('ix_competencies_school_id'), 'competencies', ['school_id'], unique=False)
    op.alter_column('competency_external_invites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('competency_external_invites', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('competency_external_invites', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('competency_external_invites', 'opened_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('competency_external_invites', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('competency_external_invites', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_external_invite_token_hash'), table_name='competency_external_invites')
    op.drop_constraint(op.f('uq_external_invite_token'), 'competency_external_invites', type_='unique')
    op.create_index(op.f('ix_competency_external_invites_school_id'), 'competency_external_invites', ['school_id'], unique=False)
    op.create_index(op.f('ix_competency_external_invites_token_hash'), 'competency_external_invites', ['token_hash'], unique=True)
    op.alter_column('competency_external_scores', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('competency_external_scores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_competency_external_scores_school_id'), 'competency_external_scores', ['school_id'], unique=False)
    op.create_index(op.f('ix_competency_goals_school_id'), 'competency_goals', ['school_id'], unique=False)
    op.create_index(op.f('ix_competency_peer_labels_school_id'), 'competency_peer_labels', ['school_id'], unique=False)
    op.create_index(op.f('ix_competency_reflections_school_id'), 'competency_reflections', ['school_id'], unique=False)
    op.create_index(op.f('ix_competency_rubric_levels_school_id'), 'competency_rubric_levels', ['school_id'], unique=False)
    op.create_index(op.f('ix_competency_self_scores_school_id'), 'competency_self_scores', ['school_id'], unique=False)
    op.create_index(op.f('ix_competency_teacher_observations_school_id'), 'competency_teacher_observations', ['school_id'], unique=False)
    op.create_index(op.f('ix_competency_windows_school_id'), 'competency_windows', ['school_id'], unique=False)
    op.alter_column('evaluations', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_feedback_summaries_school_id'), 'feedback_summaries', ['school_id'], unique=False)
    op.alter_column('grades', 'grade',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('uq_groups_school_course_team'), table_name='groups', postgresql_where='(team_number IS NOT NULL)')
    op.create_index(op.f('ix_groups_course_id'), 'groups', ['course_id'], unique=False)
    op.create_index(op.f('ix_learning_objectives_id'), 'learning_objectives', ['id'], unique=False)
    op.create_index(op.f('ix_learning_objectives_school_id'), 'learning_objectives', ['school_id'], unique=False)
    op.create_index(op.f('ix_project_assessments_group_id'), 'project_assessments', ['group_id'], unique=False)
    op.create_index(op.f('ix_rubric_criterion_learning_objectives_id'), 'rubric_criterion_learning_objectives', ['id'], unique=False)
    op.create_index(op.f('ix_rubric_criterion_learning_objectives_school_id'), 'rubric_criterion_learning_objectives', ['school_id'], unique=False)
    op.create_index(op.f('ix_teacher_courses_school_id'), 'teacher_courses', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_courses_school_id'), table_name='teacher_courses')
    op.drop_index(op.f('ix_rubric_criterion_learning_objectives_school_id'), table_name='rubric_criterion_learning_objectives')
    op.drop_index(op.f('ix_rubric_criterion_learning_objectives_id'), table_name='rubric_criterion_learning_objectives')
    op.drop_index(op.f('ix_project_assessments_group_id'), table_name='project_assessments')
    op.drop_index(op.f('ix_learning_objectives_school_id'), table_name='learning_objectives')
    op.drop_index(op.f('ix_learning_objectives_id'), table_name='learning_objectives')
    op.drop_index(op.f('ix_groups_course_id'), table_name='groups')
    op.create_index(op.f('uq_groups_school_course_team'), 'groups', ['school_id', 'course_id', 'team_number'], unique=True, postgresql_where='(team_number IS NOT NULL)')
    op.alter_column('grades', 'grade',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_index(op.f('ix_feedback_summaries_school_id'), table_name='feedback_summaries')
    op.alter_column('evaluations', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_competency_windows_school_id'), table_name='competency_windows')
    op.drop_index(op.f('ix_competency_teacher_observations_school_id'), table_name='competency_teacher_observations')
    op.drop_index(op.f('ix_competency_self_scores_school_id'), table_name='competency_self_scores')
    op.drop_index(op.f('ix_competency_rubric_levels_school_id'), table_name='competency_rubric_levels')
    op.drop_index(op.f('ix_competency_reflections_school_id'), table_name='competency_reflections')
    op.drop_index(op.f('ix_competency_peer_labels_school_id'), table_name='competency_peer_labels')
    op.drop_index(op.f('ix_competency_goals_school_id'), table_name='competency_goals')
    op.drop_index(op.f('ix_competency_external_scores_school_id'), table_name='competency_external_scores')
    op.alter_column('competency_external_scores', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('competency_external_scores', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_competency_external_invites_token_hash'), table_name='competency_external_invites')
    op.drop_index(op.f('ix_competency_external_invites_school_id'), table_name='competency_external_invites')
    op.create_unique_constraint(op.f('uq_external_invite_token'), 'competency_external_invites', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_external_invite_token_hash'), 'competency_external_invites', ['token_hash'], unique=False)
    op.alter_column('competency_external_invites', 'revoked_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('competency_external_invites', 'submitted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('competency_external_invites', 'opened_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('competency_external_invites', 'sent_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('competency_external_invites', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('competency_external_invites', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_competencies_school_id'), table_name='competencies')
    op.drop_index(op.f('ix_audit_logs_school_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_project_notes_team_id'), table_name='project_notes')
    op.drop_index(op.f('ix_project_notes_student_id'), table_name='project_notes')
    op.drop_index(op.f('ix_project_notes_learning_objective_id'), table_name='project_notes')
    op.drop_index(op.f('ix_project_notes_id'), table_name='project_notes')
    op.drop_index(op.f('ix_project_notes_created_by'), table_name='project_notes')
    op.drop_index(op.f('ix_project_notes_context_id'), table_name='project_notes')
    op.drop_index('ix_project_note_team', table_name='project_notes')
    op.drop_index('ix_project_note_student', table_name='project_notes')
    op.drop_index('ix_project_note_omza', table_name='project_notes')
    op.drop_index('ix_project_note_created_at', table_name='project_notes')
    op.drop_index('ix_project_note_context_type', table_name='project_notes')
    op.drop_table('project_notes')
    op.drop_index(op.f('ix_project_notes_contexts_school_id'), table_name='project_notes_contexts')
    op.drop_index(op.f('ix_project_notes_contexts_id'), table_name='project_notes_contexts')
    op.drop_index(op.f('ix_project_notes_contexts_evaluation_id'), table_name='project_notes_contexts')
    op.drop_index(op.f('ix_project_notes_contexts_created_by'), table_name='project_notes_contexts')
    op.drop_index(op.f('ix_project_notes_contexts_course_id'), table_name='project_notes_contexts')
    op.drop_index(op.f('ix_project_notes_contexts_class_name'), table_name='project_notes_contexts')
    op.drop_index('ix_project_notes_context_school_course', table_name='project_notes_contexts')
    op.drop_index('ix_project_notes_context_created_by', table_name='project_notes_contexts')
    op.drop_table('project_notes_contexts')
    # ### end Alembic commands ###
