"""add FK users.school_id -> schools.id

Revision ID: 70278d654e6f
Revises: 5319ae216851
Create Date: 2025-10-10 23:02:11.684217

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "70278d654e6f"
down_revision: Union[str, None] = "5319ae216851"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "users", "schools", ["school_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    # ### end Alembic commands ###
